namespace PinnacleSample.Services.PartAvailabilityService
{
    /**
     * PinnacleSample.PartAvailabilityService was generated by Visual Studio. So, it is better if having a wrapper in case of enhancing PinnacleSample.PartAvailabilityService, such as: logging, implementation for more logic.
     * PartAvailabilityService is a wrapper for PinnacleSample.PartAvailabilityService. It is used for consuming API exposed by PinnacleSample.PartAvailabilityService.
     * **/
    public class PartAvailabilityService : IPartAvailabilityService
    {
        public PartAvailabilityService()
        {

        }

        public int GetAvailability(string stockCode)
        {
            using (PartAvailabilityServiceClient _PartAvailabilityService = new PartAvailabilityServiceClient())
            {
                return _PartAvailabilityService.GetAvailability(stockCode);
            }
        }
    }
}
